services:
  flow2api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3101:8000"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    restart: unless-stopped
  captcha-solver:
    build:
      context: .
      dockerfile: Dockerfile.captcha
    environment:
      - WS_URL=ws://flow2api:8000/ws/captcha
      - AUTH_KEY=
    depends_on:
      - flow2api
    restart: unless-stopped
    shm_size: '512m'
